### ISSUE TITLE
Custom userValidator no longer passed reference to MessageBox plugin

### ISSUE THREAD

**Issue by wphampton** [ColdBox/cbox-security#1]
For anyone making the transition from ColdBox 3 to ColdBox 4 by now using the cbsecurity module, be aware that this module no longer passes a reference to the MessageBox plugin when it calls your userValidator function.  Your userValidator function used to need to handle three parameters [as seen in the wiki](http://wiki.coldbox.org/wiki/Security.cfm#Custom_Security:_Validator_Object) but now just needs to support two.  Maybe some additional up to date examples would be helpful for this unless I just missed it somewhere.

**SecurityService.cfc**
```java
component singleton {
  // Inject the MessageBox module yourself
  property name="MessageBox" inject="MessageBox@cbmessagebox";

  // Custom User Validator
  boolean function userValidator(struct rule, any controller){
    var isAllowed = YourSpecialLogic();
    
    if (!isAllowed) {
      MessageBox.warning("Permission denied.");
    }

    return isAllowed;
  }
}
```

**Comment by lmajano** [comment]
Yes, I will update the docs on this.
